stages:
  - deploy

variables:
  DOCKER_IMAGE: mijewelmj/new-wordpress-image:latest

before_script:
  - apt-get update && apt-get install -y docker.io

deploy_staging:
  stage: deploy
  tags:
    - job1run1

  script:
    - echo "Deploying to the staging server..."
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - touch ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - echo "$STAGING_SSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo "Copying files to the staging server..."
    - scp -o ~/.ssh/id_rsa docker-compose.yml/ raichel@$STAGING_IP:/home/raichel/wordpress
    - scp -o ~/.ssh/id_rsa nginx.conf raichel@$STAGING_IP:/home/raichel/wordpress
    - echo "Executing docker-compose on the staging server..."
    - ssh -0 ~/.ssh/id_rsa raichel@$STAGING_IP bash -c "'
        cd /home/raichel/wordpress/docker-compose/ &&
        docker-compose down &&
        docker-compose up -d
      '"
  only:
    refs:
      - staging
  environment:
    name: staging
  when: manual 
deploy_production:
  stage: deploy
  script:
    - echo "Deploying to the production server..."
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$PRODUCTION_SSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - touch ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    #- ssh-keyscan -H $PRODUCTION_IP >> ~/.ssh/known_hosts
    - eval $(ssh-agent -s)
    - ssh-add ~/.ssh/id_rsa
    - ssh-add -l
    - echo "Copying files to the production server..."
    - scp -o StrictHostKeyChecking=no docker-compose.yml raichel@$PRODUCTION_IP:/home/raichel/wordpress/
    - scp -o StrictHostKeyChecking=no nginx.conf raichel@$PRODUCTION_IP:/home/raichel/wordpress/
    - echo "Executing docker-compose.yml on the production server..."
    - ssh -o StrictHostKeyChecking=no raichel@$PRODUCTION_IP bash -c "'
        cd /home/raichel/wordpress/ &&
        docker-compose down &&
        docker-compose up -d
      '"

      
  only:
    refs:
      - main
  environment:
    name: production
  when: manual